from __future__ import annotations

TEST_TOKEN = "SYNTHETIC_TOKEN_FOR_TESTING"
TEST_ENCRYPTED_PERSON_ID = "SYNTHETIC_ENCRYPTED_PERSON_ID"
TEST_ACCOUNT_ID = "0000000000"
TEST_ACCOUNT_KEY = "a1b2c3d4e5f6a7b8"
